global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

# Configuration for scraping individual services
scrape_configs:

  - job_name: 'prometheus'
    dns_sd_configs:
      - names: ['prometheus-discovery']
        port: 9090
        type: A # Render service discovery uses A records
        refresh_interval: 5s # Refresh the list of targets every 5 seconds

  - job_name: 'theirstackbackend' # Replace w/ your service's name
    dns_sd_configs:
      - names: ['theirstackbackend-discovery'] # Replace w/ your service's name + '-discovery'
        port: 9090 # Replace w/ the port for your service's metrics endpoint
        type: A
        refresh_interval: 5s
