global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

# Configuration for scraping individual services
scrape_configs:

  # Uncomment to add a job for scraping another Render service
  - job_name: 'theirstackbackend' # Replace w/ your service's name
    basic_auth:
      username: GRAFANA_USERNAME
      password: GRAFANA_PASSWORD
    dns_sd_configs:
      - names: ['theirstackbackend-discovery'] # Replace w/ your service's name + '-discovery'
        port: 10000 # Replace w/ the port for your service's metrics endpoint
        type: A
        refresh_interval: 5s
remote_write:
  - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
    basic_auth:
      username: GRAFANA_USERNAME
      password: GRAFANA_PASSWORD